"""phase5: add user_settings table for dual-track mode

Revision ID: 0a45d96ff7fb
Revises: 8360f4e545f8
Create Date: 2026-03-06 12:38:54.623271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a45d96ff7fb'
down_revision: Union[str, Sequence[str], None] = '8360f4e545f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_custom_mode', sa.Boolean(), nullable=False),
    sa.Column('stt_provider', sa.Enum('deepgram', name='stt_provider_enum'), nullable=True),
    sa.Column('llm_provider', sa.Enum('siliconflow', 'openrouter', name='llm_provider_enum'), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('tts_provider', sa.Enum('cartesia', name='tts_provider_enum'), nullable=True),
    sa.Column('encrypted_stt_key', sa.Text(), nullable=True),
    sa.Column('encrypted_llm_key', sa.Text(), nullable=True),
    sa.Column('encrypted_tts_key', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # PostgreSQL 不会随 DROP TABLE 自动删除枚举类型
    op.execute("DROP TYPE IF EXISTS stt_provider_enum")
    op.execute("DROP TYPE IF EXISTS llm_provider_enum")
    op.execute("DROP TYPE IF EXISTS tts_provider_enum")
    # ### end Alembic commands ###
