"""phase6_add_individual_validation_status

Revision ID: 20a8c7f2bc2f
Revises: 847c9f49681c
Create Date: 2026-03-07 01:06:12.122128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a8c7f2bc2f'
down_revision: Union[str, Sequence[str], None] = '847c9f49681c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('stt_is_valid', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_settings', sa.Column('llm_is_valid', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_settings', sa.Column('tts_is_valid', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'tts_is_valid')
    op.drop_column('user_settings', 'llm_is_valid')
    op.drop_column('user_settings', 'stt_is_valid')
    # ### end Alembic commands ###
