"""phase3: add emotion_state to transcripts

Revision ID: 8360f4e545f8
Revises: c82f834e00e0
Create Date: 2026-03-02 16:49:52.884742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8360f4e545f8"
down_revision: Union[str, Sequence[str], None] = "c82f834e00e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcripts", sa.Column("emotion_state", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcripts", "emotion_state")
    # ### end Alembic commands ###
