"""phase6_byok_auth_refactor

Revision ID: 847c9f49681c
Revises: 0a45d96ff7fb
Create Date: 2026-03-06 23:46:08.796268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "847c9f49681c"
down_revision: Union[str, Sequence[str], None] = "0a45d96ff7fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_settings",
        sa.Column(
            "is_custom_verified", sa.Boolean(), server_default="false", nullable=False
        ),
    )

    # 修改 is_custom_mode 的默认值为 True
    op.alter_column("user_settings", "is_custom_mode", server_default="true")
    # 对于存量数据，新逻辑下所有用户默认为自备密钥模式，且未经验证
    op.execute(
        "UPDATE user_settings SET is_custom_mode = true, is_custom_verified = false"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_settings", "is_custom_mode", server_default="false")
    op.drop_column("user_settings", "is_custom_verified")
    # ### end Alembic commands ###
